### ISSUE TITLE
Libtag segfaults on mkv files

### ISSUE THREAD

**Issue by ltworf** [taglib/taglib#880] opened 2018-09-24 18:02 UTC
Ok you don't want to support them.

Segfault is not the answer.

**Comment by scotchi** [comment] 2018-09-24 18:04
Can you paste in the code that's segfaulting?

**Comment by ltworf** [comment] 2018-09-24 20:28
```
TagLib::FileRef tags(i.filePath().toStdString().c_str());
```

where i is a QFile pointing to a mkv.

**Comment by scotchi** [comment] 2018-09-24 21:09
That works just fine here (tested on macOS and Linux).  I believe the problem is that you're using `c_str()` from a temporary variable.

**Comment by scotchi** [comment] 2018-09-24 22:05
To be clearer, this is the code I used:

```
#include <fileref.h>
int main(int argc, const char *argv[])
{
    TagLib::FileRef tags(argv[1]);
    return 0;
}
```

**Comment by ltworf** [comment] 2018-09-26 18:57
I have ii  libtag1v5:amd64                               1.11.1+dfsg.1-0.2+b1           amd64        audio meta-data library

Is it a different version than latest release?

**Comment by scotchi** [comment] 2018-09-27 12:28
Yes, that's the version I was testing with.

**Comment by scotchi** [comment] 2018-10-09 08:51
Closing this for now unless there's some further info at some point.  At this point it's not possible to reproduce the issue you're seeing.

**Closed by scotchi** 2018-10-09 08:51 UTC

**Comment by ltworf** [comment] 2018-10-11 19:56
I was not aware I had to check isNull() besides isEmpty()
