### ISSUE TITLE
FileTypeResolver virtual destructor

### ISSUE THREAD

**Issue by gfgit** [taglib/taglib#979] opened 2020-12-06 16:57 UTC
Abstract class:
`class FileTypeResolver`
declared in  [fileref.h, line L92](https://github.com/taglib/taglib/blob/91b00b17b253dad0d7037232ef7033c88bdd28bd/taglib/fileref.h#L92)
**has no virtual destructor** but is deleted in the list destructor:
`ResolverList fileTypeResolvers;` at [fileref.cpp line 61](https://github.com/taglib/taglib/blob/91b00b17b253dad0d7037232ef7033c88bdd28bd/taglib/fileref.cpp#L61)

**Comment by ufleisch** [comment] 2020-12-06 19:31
Duplicate of #477

**Closed by ufleisch** 2020-12-06 19:31 UTC
