### ISSUE TITLE
Does taglib Support MKV?

### ISSUE THREAD

**Issue by odemiral** [taglib/taglib#839] opened 2017-10-20 01:57 UTC
Apologies if this has been asked before, I was under the impression that taglib supports videos as well but the description specifically specifies the library is for audio formats. 

Can anyone please confirm whether or not editing mkv tags supported?

Thanks!

**Comment by malaterre** [comment] 2018-01-29 12:43
Duplicate of #387

**Comment by scotchi** [comment] 2018-01-29 12:53
TagLib is specifically for audio.

**Closed by scotchi** 2018-01-29 12:53 UTC
