### ISSUE TITLE
TagLib 2.0.x cannot read album, title, genre of some MP3 files

### ISSUE THREAD

**Issue by ghost** [taglib/taglib#1228] opened 2024-05-12 17:13 UTC
I enclose a sample MP3 file. TagLib was able to parse the tags in 1.13.1. But after the update to TagLib 2.0.1, this file's album, title, and genre are read as empty strings.

This feels like a bug — especially because ffmpeg and all GUI tools that I happen to have are able to read the file's album, title, and genre just fine (plus, remember, TagLib _used_ to be able to read them).

[1-03 The Gnu Song.mp3.zip](https://github.com/taglib/taglib/files/15287101/1-03.The.Gnu.Song.mp3.zip)

**Comment by sbooth** [comment] 2024-05-12 19:58
This file has an ID3v2.2 tag, and I believe the root of the problem is that ID3v2.2 and ID3v2.4 have different frame header sizes (6 vs. 10 bytes), and internally for ID3v2.2 `PIC` frames TagLib swaps out the v2.2 header with a v2.4 header. This used to be accounted for by 

https://github.com/taglib/taglib/blob/322085f90e328dd588c967f9623d3cd5faf8892a/taglib/mpeg/id3v2/id3v2tag.cpp#L818

but changed to

https://github.com/taglib/taglib/blob/ceb142c9bded9f0803d79658403f368dd3d60fae/taglib/mpeg/id3v2/id3v2tag.cpp#L818

This leads to the frames following `PIC` being ignored because the subsequent read offsets are off by 4.

**Comment by ufleisch** [comment] 2024-05-14 12:57
@sbooth Thanks for the analysis, you are right. The dynamic `headerSize()` would work correctly for ID3v2.2 frames, however, it is called on the converted ID3v2.4 frame. I have created a PR #1229 to fix this.

**Comment by ufleisch** [comment] 2024-06-02 13:11
Fixed with #1229.

**Closed by ufleisch** 2024-06-02 13:11 UTC
