### ISSUE TITLE
"Invalid atom type" error with m4a files created by Android

### ISSUE THREAD

**Issue by garrybrady** [taglib/taglib#1230] opened 2024-05-14 15:19 UTC
I've built TagLib 2.0.1 from source on macOS and have been using the examples tagreader / tagwriter.

All works well apart from m4a files created on Android devices. 

I've used the app I develop, a selection of voice recorders and also several different Android devices but all combinations display "Invalid atom type".

I've attached a sample recording.

[android.m4a.zip](https://github.com/taglib/taglib/files/15310532/android.m4a.zip)

**Comment by garrybrady** [comment] 2024-05-14 15:55
Have tested on both Intel & M1 chips.

**Comment by sbooth** [comment] 2024-05-16 11:18
The issue is with the `ilst` box which contains a box of type 0x00000001 and size 26. TagLib checks that box types contain printable characters:

https://github.com/taglib/taglib/blob/ebf4c5bbb1ce85a71764122cbc3cc3f556e66586/taglib/mp4/mp4atom.cpp#L100

I believe that the box type *normally* contains printable characters but I haven't yet found a reference *requiring* printable characters. I also believe that unknown box types should be ignored and skipped. 

MP4 is based on the QuickTime file format and [Apple says](https://developer.apple.com/documentation/quicktime-file-format/atoms):

> Type
> A 32-bit integer that contains the type of the atom. This can often be usefully treated as a four-character field with a mnemonic value, such as 'moov' (0x6D6F6F76) for a movie atom, or 'trak' (0x7472616B) for a track atom, but non-ASCII values (such as 0x00000001) are also used. Knowing an atom’s type allows you to interpret its data. An atom’s data can be arranged as any arbitrary collection of fields, tables, or other atoms. The data structure is specific to the atom type. An atom of a given type has a defined data structure. If your application encounters an atom of an unknown type, it should not attempt to interpret the atom’s data. Use the atom’s size field to skip this atom and all of its contents.

I think it probably makes sense for TagLib to skip unknown boxes.

**Comment by garrybrady** [comment] 2024-05-16 13:46
That's great, thanks. Have tried removing the check for printable chars and all now seems fine on all files.

**Comment by ufleisch** [comment] 2024-06-02 13:12
Fixed by #1231.

**Closed by ufleisch** 2024-06-02 13:12 UTC
