### ISSUE TITLE
TagLib occasionally corrupts M4A files?

### ISSUE THREAD

**Issue by dukeyin** [taglib/taglib#293] opened 2013-10-05 20:47 UTC
http://forums.mp3tag.de/index.php?showtopic=17809

I was running some test code on Android.  Resulting tag can still be read by TagLib, foobar2000, iTunes, and Windows Explorer, but the end of the audio stream is lost!

I am pretty sure all I did was add a short comment ("NEW Comm"), where there did not yet exist a comment:
jstring value = (jstring) env->GetObjectArrayElement(valueArray, i);
std::wstring wValue = Java_To_WStr(env, value);
audioFile.tag()->setComment(wValue);

I am sure this code did not run, but I use this for custom tags:
audioFile->tag()->itemListMap()[keyStr] = TagLib::StringList(wValue);

I have been trying to reproduce this bug but am having difficulty doing so.  I repeated my steps and produced a correct file instead of a broken one.  And strangely, when I compared the two files in HxD, I got "the chosen files are identical. the file sizes are different, though!"

I'm not sure where the problem may lie, and I guess I don't know enough about files - why would my hex editor tell me 2 files are identical when the filesizes are different?  In Windows, the "size on disk" is identical (6,660,096 bytes) but the "size" differs (6,658,750 vs 6,659,042).  Could this be a problem with TagLib, or is it more likely a problem with the storage system (Android device) I was running on?

I can provide the before and 2 after files to anyone who wants to investigate (I suppose I shouldn't post the links publicly).

**Comment by scotchi** [comment] 2015-05-19 17:53
Hi -- do you have any more specific steps that you took there that caused the corruption?  With the current master branch I couldn't reproduce the problem just by removing an item from that file and saving.  Here's what I used:

    void testRemoveFields()
    {
      ScopedFileCopy copy("no-tags_original", ".m4a");
      string name = copy.fileName();
      {
        MP4::File f(name.c_str());
        MP4::Tag *t = f.tag();
        CPPUNIT_ASSERT(t->itemMap().size() == 30);
        t->removeItem("tmpo");
        CPPUNIT_ASSERT(t->itemMap().size() == 29);
        f.save();
      }
      {
        MP4::File f(name.c_str());
        MP4::Tag *t = f.tag();
        CPPUNIT_ASSERT(t->itemMap().size() == 29);
      }
    }

**Comment by TsudaKageyu** [comment] 2015-07-31 05:59
Hi @dukeyin, is this related to #619? In other words, did you call ```save()``` twice?

The bug at #619 occurs when :
* Open a MP4 file doesn't have a tag.
* Call ```MP4::File::save()``` twice (or more) without closing the file.

**Comment by FestusHagen** [comment] 2015-12-21 13:17
#683 Closes this?

-Enjoy

**Closed** 2015-12-21 13:19 UTC
Labels: needmoreinfo
