### ISSUE TITLE
2.0: test suite fails

### ISSUE THREAD

**Issue by kloczek** [taglib/taglib#1213] opened 2024-01-24 11:28 UTC
Looks like last version test suite fails
<details>

```console
+ cd taglib-2.0
+ /usr/bin/ctest --test-dir x86_64-redhat-linux-gnu --output-on-failure --force-new-ctest-process -j48
Internal ctest changing into directory: /home/tkloczko/rpmbuild/BUILD/taglib-2.0/x86_64-redhat-linux-gnu
Test project /home/tkloczko/rpmbuild/BUILD/taglib-2.0/x86_64-redhat-linux-gnu
    Start 1: test_runner
1/1 Test #1: test_runner ......................Subprocess aborted***Exception:   0.09 sec
Running TestAIFF::testAiffProperties : OK
TestAIFF::testAiffCProperties : OK
TestAIFF::testSaveID3v2/usr/include/c++/14/bits/unique_ptr.h:447: typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp, _Dp>::operator*() const [with _Tp = TagLib::StringList::StringListPrivate; _Dp = std::default_delete<TagLib::StringList::StringListPrivate>; typename std::add_lvalue_reference<_Tp>::type = TagLib::StringList::StringListPrivate&]: Assertion 'get() != pointer()' failed.


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.09 sec

The following tests FAILED:
        1 - test_runner (Subprocess aborted)
Errors while running CTest
```
</details>

**Comment by kloczek** [comment] 2024-01-24 18:23
> What compiler are you using? Can you post your build configuration?

gcc 14 from fedora rawhide.

**Comment by ufleisch** [comment] 2024-01-27 10:08
Duplicate of #1211

**Closed by ufleisch** 2024-01-27 10:08 UTC
