### ISSUE TITLE
File length in milliseconds

### ISSUE THREAD

**Issue by DidierMalenfant** [taglib/taglib#503] opened 2015-02-15 06:56 UTC
I need to get the length of the file in milliseconds.

Most formats let me recalculate the length using sampleFrames() and sampleRate() but mp4 and mpeg don't expose enough info for me to do this externally of the class. The precision seems to be there but it's truncated to seconds during the calculations.

Most of you guys here have more experience with the library than I do, would it be ok to expose more data from those two classes in order to calculate a more precise length?

I could also create a new property lengthInMilliseconds and calculate that inside the class itself but that seems more disruptive.

Thoughts?

**Comment by sbooth** [comment] 2015-02-16 02:55
This is something I've wanted to bring up as well.  I currently use [mp4v2] (https://code.google.com/p/mp4v2/) in lieu of TagLib for MP4 files because it has a fuller feature set.  TagLib's MP4 support is functional but doesn't have the same kind of support for the format as it does for FLAC or MP3.  This is partly because the MP4 spec is not very open.  I'd like to improve the MP4 support in TagLib to expose not only the type of information that @DidierMalenfant asked about but also to duplicate some of the features that mp4v2 has but TagLib lacks.  This would probably involve making some type of atom class public but I am not sure what a user-friendly interface should look like.

**Comment by TsudaKageyu** [comment] 2015-02-16 04:43
This is a feature that I have been wanted. I think that implementation itself is not very difficult. As @DidierMalenfant pointed out, the precision seems to be there.
About the interface, I have some ideas but they are confusing with ```length()```. For example:
```
// audioproperties.h

/*!
 * Returns the duration of the file in milliseconds.
 */
virtual int duration() const = 0;
```
So far I don't have an idea which is not confusing with existing ```length()``` function. I'd like to wait for someone to bring us a good idea.

**Comment by DidierMalenfant** [comment] 2015-02-16 05:02
I'm a big fan of using as few comments as possible, especially in cases like this. My preference would be something like:
```
// audioproperties.h

virtual int lengthInMilliseconds() const = 0;
```
which has the advantage of being clear, self-commenting and self explanatory even in places where the method is called. Saves you having to look up the header to find out what the unit it.

I do understand that this is not the standard way of naming things in taglib so I don't want this to stand out, and also to be available in parallel with the regular ```length()``` which is why I was thinking of exposing ways for the user to calculate the more precise length instead, like ```samplefames()``` in the other classes.

Regarding @sbooth's comment. I think anything that all format have in common should be in audio properties but anything MP4 specific could be added via an interface to easily parse MP4 Atoms, like ID3V2 tags can be parsed for MP3/AIFF/etc...

**Comment by TsudaKageyu** [comment] 2015-02-16 17:51
I tried it and confirmed that it's easy to implement.
But it will interfere with #496, so I need to wait for it to be merged.

**Comment by TsudaKageyu** [comment] 2015-06-20 18:11
I created some pull requests #555-#568 in response to this issue a few months ago.
I self-reviewed them several times, and I now think they deserve to be merged. Has somebody reviewed them?

**Closed** 2015-07-31 16:35 UTC
Labels: wishlist
