### ISSUE TITLE
MP3 strip bug

### ISSUE THREAD

**Issue by whatdoineed2do** [taglib/taglib#913] opened 2019-07-17 14:12 UTC
Update: Fix in pr https://github.com/taglib/taglib/issues/914

There is MP3 stripping bug if you have a file with both APE and ID3v1 tag.

If you try to strip using `strip(TagLib::MPEG::File::ID3v1 | TagLib::MPEG::File::APE);` or calling `strip(TagLib::MPEG::File::ID3v1)` *before* `strip(TagLib::MPEG::File::APE)` then saving the file results in the ID3v1 untouched.

However if your file does not have APE tag then this works as expected.

Here is the code to demonstrate:
```
#include <iostream>
#include <taglib/mpegfile.h>

int main(int argc, char *argv[])
{
    if (argc != 3) {
        return 1;
    }
    try
    {
        TagLib::MPEG::File  f(argv[2], false);

	switch (*argv[1])
	{
            case '0':
// this is the only item that works
	      f.strip(TagLib::MPEG::File::APE);
	      f.strip(TagLib::MPEG::File::ID3v1);
	      break;

// these leave the ID3v1 in the file when there is APE + ID31
// if there is ONLY id3v1 then this is removes the id3v1 tag
            case '1':
	      f.strip(TagLib::MPEG::File::ID3v1);
	      f.strip(TagLib::MPEG::File::APE);
	      break;

	    default:
	      f.strip(TagLib::MPEG::File::ID3v1 | TagLib::MPEG::File::APE);
	}

        f.save(TagLib::MPEG::File::ID3v2);
    }
    catch (const std::exception& ex)
    {
        std::cerr << ex.what() << std::endl;
    }
    return 0;
}
```

**Comment by Moonbase59** [comment] 2019-07-17 18:54
Unfortunately, this is also true when using "stripOthers" in f.save() like so:
```c
f.save(TagLib::MPEG::File::ID3v2, true, 3);
```

**Comment by Moonbase59** [comment] 2019-07-17 21:14
Possible duplicate of #835

**Comment by whatdoineed2do** [comment] 2019-07-17 22:33
Ah yes. This is indeed the same - I had forgotten that I raised the same issue 2 years previous!

**Comment by Moonbase59** [comment] 2019-07-18 11:13
Apart from a few disastrous bugs, taglib is a great library and used by many (I think I remember EasyTag, Clementine, Mixxx, loudgain, …). With all this groundwork laid out, it’d be a shame to see it go under—or maintainers having to patch it themselves.

I’d REALLY love to see a new fixed version to be picked up by the distros, because end users simply can’t be expected to fix things and compile it themselves!

**Comment by whatdoineed2do** [comment] 2019-07-21 13:25
Even more annoyingly, the workaround (strip APE before ID3v1) only works for some files - 2 different files demonstrating this added to the original post.

**Closed** 2019-07-25 02:57 UTC
