### ISSUE TITLE
ID3v1 tags being returned nul character padded

### ISSUE THREAD

**Issue by DaveTBlake** [taglib/taglib#741] opened 2016-05-04 05:39 UTC
Noticed a change in Taglib 1.10 from 1.9 in the way ID3v1 tags are returned and wondering if this is deliberate or a side-effect, and either way is it desireable? I have not been able to test 1.11 yet to see what happens there.

In 1.9 accessing ID3v1 tags using `to8Bit` returned a standard nul terminated string the size of the actual text as happens for ID3v2, but in 1.10 this string is always padded with nul characters to a fixed size. This means that using size() or empty() on the returned string is meaningless. Generally the trailing nul padding is not too much an issue, but it makes it harder to detect an empty tag. The wiki says that this should return nul,  but  for ID3v1 it is returning a string of nul characters instead.

If 1.10 behaviour is to be kept, then it would be good to highlight this change in the release notes.

**Comment by FestusHagen** [comment] 2016-05-07 08:18
Unable to reproduce, Can you provide an example?

**Comment by DaveTBlake** [comment] 2016-05-07 14:28
Festus I understand from others that v1.11 does not have this issue (behaves like 1.9), so simply using the newest version may be the fix. 

However if you would like to check what is happening in v1.10  then tag a mp3 file with ID3v1 tags for artist = "artist1", album = "", title = "Test Song" say. `id3v1->artist().to8Bit(true)` etc. will always return a string size 30, regardless of the artist name, with the trailing spaces filled with '\0'.  In the example `id3v1->album().to8Bit(true)` is all '\0', and size() and empty() is unable to detect it is an empty string.

**Comment by FestusHagen** [comment] 2016-05-08 01:29
Like I said, Unable to reproduce ... With .9, .10 or .11
![pr741](https://cloud.githubusercontent.com/assets/2348136/15095564/9bb5ab1c-149a-11e6-925e-45df2abb070d.jpg)

However, if you say it's fixed in v1.11 the issue is moot and this issue is closable.

**Comment by scotchi** [comment] 2016-05-08 01:31
I'm not sure that from what he described that just printing the values would show the problem, as null characters aren't printable.  Can you do a minor change there to print the string lengths?

**Comment by FestusHagen** [comment] 2016-05-08 01:41
As in ...
![pr741a](https://cloud.githubusercontent.com/assets/2348136/15095588/4ef73b18-149c-11e6-99f2-eeba16616e18.jpg)
```
    String str = id3v1tag->title().to8Bit(true);
    cout << "  TagLib version v" << TAGLIB_MAJOR_VERSION << "." << TAGLIB_MINOR_VERSION << endl;
    cout << "    title   - \"" << id3v1tag->title().to8Bit(true)   << "\"" << " - Size=" << id3v1tag->title().size() << " - str.size()=" << str.size() << endl;
    cout << "    artist  - \"" << id3v1tag->artist()  << "\"" << endl;
```

**Comment by scotchi** [comment] 2016-05-08 01:44
Yes, that should better test the case reported.  Can you try that against 1.10?  (If it checks out, it sounds like a reasonably subtle bug that may be caused by a change in the toolkit, which is why I'm somewhat interested in this.)

**Comment by FestusHagen** [comment] 2016-05-08 01:54
That is against v1.10 ... Note the Taglib version in the screen print ... and the code that prints it.

I have run this same code against v1.9, 1.10 (as shown above) and v1.11 with the same results.

**Comment by scotchi** [comment] 2016-05-08 01:54
Ah, sorry, didn't read closely enough.

**Comment by FestusHagen** [comment] 2016-05-08 02:09
Shouldn't the `id3v1tag->title().size()` in the first screen print been sufficient?

**Comment by DaveTBlake** [comment] 2016-05-08 07:34
Guys thanks for looking at this. Clearly you are not seeing the issue in your test, which is odd, is this possibly compiler specific?  I am looking at debug in VS2015 C++ (of Kodi), size is 30 for all the ID3v1 tags regardless of content for 1.10. If it is somehow down to how the different verions of TagLib have been built what could that be?

**Comment by scotchi** [comment] 2016-05-08 07:35
Could you provide us with a minimal example of where you're seeing the problem?  i.e. 10 lines or something...  That way we can make sure we're on the same page before proceeding.

**Comment by DaveTBlake** [comment] 2016-05-08 08:01
Scotchi, I would love to, and I understand why you would want that, but not sure I can. 

What Festus is testing is the right area, and although burried in a much bigger project it effectively just calls `id3v1->album().to8Bit(true)`. Kodi changed from using 1.9 to 1.10, and we started geting odd behaviour that has been pinned down to the strings returned in ID3v1 tags.

For what it is worth the unit involved is here https://github.com/xbmc/xbmc/blob/master/xbmc/music/tags/TagLoaderTagLib.cpp#226, not too hard to read but I'm not expecting you to dig into it.

**Comment by DaveTBlake** [comment] 2016-05-08 11:14
More useful could be the build of the Taglib 1.10 library that we get this nul padding issue with 
http://mirrors.kodi.tv/build-deps/win32/taglib-1.10-win32-vc140.7z

Since every application is advised to compile Taglib using the same compiler as the rest, could that be why you are not repeating the problem?

**Comment by FestusHagen** [comment] 2016-05-08 15:16
> Since every application is advised to compile Taglib using the same compiler as the rest, could that be why you are not repeating the problem?

In my opinion that is a requirement not advice ...

I build on the targeted OS using the same toolchain, I build and test on 3 OS's with 4 toolchains. (No Linux here)

**Comment by DaveTBlake** [comment] 2016-05-09 08:53
Unfortunately we seem to be getting the same padding behaviour  with 1.11 too. It is very odd that you aren't able to repeat it.

Could someone try a test routine build on Visual Studio 2015? The change from 1.9.1 to 1.10 coinsided with a change from VS2013 to VS2015, I'm left wondering if that contributes somehow.

**Comment by scotchi** [comment] 2016-05-09 08:55
I think the burden there falls on Kodi at this point. @FestusHagen, could you maybe post your demo code so that @DaveTBlake can try it on his end?  I'm skeptical that it's a compiler issue (and at this point would guess that it's more likely that it's a bug somewhere in Kodi).

**Comment by DaveTBlake** [comment] 2016-05-09 09:07
I can see why you might think that @scotchi, but it is hard to see how Kodi could cause the padding. The Kodi code in this area has not changed. Myself I wonder about the changes to tbytevector.cpp from 1.9.1 to 1.10, but not that familiar with Taglib code.

I'm willing to do whatever I can Kodi side to understand this issue, and appreciate any assistence.

**Comment by FestusHagen** [comment] 2016-05-09 15:09
Sure @scotchi, Always willing to help ...
```
//  *
//  * It is what it is, you can do with it as you please.
//  *
//  * Just don't blame me if it teaches your computer to smoke!
//  *
//  *  -Enjoy
//  *  fh :)_~
//  *
//
#include <mpegfile.h>
#include <id3v1tag.h>

using namespace std;
using namespace TagLib;

int main(int argc, char *argv[])
{

  MPEG::File audioFile(argv[1]);
  ID3v1::Tag *id3v1tag = audioFile.ID3v1Tag();

  if(id3v1tag) {
    String str = id3v1tag->title().to8Bit(true);
    cout << "  TagLib version v" << TAGLIB_MAJOR_VERSION << "." << TAGLIB_MINOR_VERSION << endl;
    cout << "    title   - \"" << id3v1tag->title().to8Bit(true)   << "\"" << " - Size=" << id3v1tag->title().size() << " - str.size()=" << str.size() << endl;
    cout << "    artist  - \"" << id3v1tag->artist()  << "\"" << endl;
    cout << "    album   - \"" << id3v1tag->album()   << "\"" << endl;
    cout << "    year    - \"" << id3v1tag->year()    << "\"" << endl;
    cout << "    comment - \"" << id3v1tag->comment() << "\"" << endl;
    cout << "    track   - \"" << id3v1tag->track()   << "\"" << endl;
    cout << "    genre   - \"" << id3v1tag->genre()   << "\"" << endl;
  } else
    cout << "No id3v1 tag" << endl;

  return 0;
}
```

**Comment by DaveTBlake** [comment] 2016-05-09 15:49
Thanks for that @FestusHagen I will endevour to create the issue in a simple repeatable way.

In the meantime I have debug in VS2015 running on v1.11 and in VS2013 on v1.9.1 (different builds of Kodi) on two separate machines, stepping through in parallel. The nul padding seems to go deep into Taglib on 1.11, and isn't there in 1.9.1. I know that it sounds like it must be a Kodi issue but both versions of Kodi call taglib in the same way to scan the tags from the same music file.

**Comment by DaveTBlake** [comment] 2016-05-09 16:11
When I set a watch on line 460 of mpegfile.cpp for
`((((*((TagLib::ID3v1::Tag*)(((((d)->tag).d)->tags)[2]))).d)->album).d)->data` in v1.11
`((((*((TagLib::ID3v1::Tag*)((((((d)->tag).d)->tags)._MyFirst)[2]))).d)->album).d)->data` in v1.9.1
i think comparable structures, and scan a mp3 file with ID3v1 tags
in v1.9.1 is has  a size of the album text, empty when there is none.
in v1.10 and v1.11 it always has size = 30, padded with '\0'

Can you see that?

**Comment by scotchi** [comment] 2016-05-10 04:55
This is a Kodi bug.  In your ID3v1::StringHandler implementation, you explicitly initialize the length of the string to the maximum size:

https://github.com/xbmc/xbmc/blob/master/xbmc/music/tags/TagLoaderTagLib.cpp#L64

That differs from the way our String implementation copies is initialized from a ByteVector.

This produces 3 and 30:

    const char *s = "foo\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";
    cout << TagLib::String(TagLib::String(s)).length() << ' '
         << std::string(s, 30).size() << endl;

**Closed by scotchi** 2016-05-10 04:55 UTC

**Comment by scotchi** [comment] 2016-05-10 04:57
I'm not sure why you saw a change around that time -- the above does the same thing on master and v1.9.1 of TagLib, but I'd guess it was connected to replacing your internal string implementation (which shows up in the "blame" for that function in 2013.

**Comment by DaveTBlake** [comment] 2016-05-11 21:53
Many thanks for locating this @scotchi, and apologies for taking both your time. It is hard to see quite how that   ID3v1::StringHandler implementation didn't cause any issues in Kodi 15.1 and 16 (using 1.9.1 and VS2013) and only the switch to 1.10 and VS2015 brought it out. As you suggest, it must be string handling related but it sure isn't obvious.

Sorry for delay in my response but I've been off line with a faulty internet connection, all your help has been greatly appreciated.
