### ISSUE TITLE
Access to less standard ID3 fields

### ISSUE THREAD

**Issue by ryanfrancesconi** [taglib/taglib#884] opened 2019-01-02 01:44 UTC
I need access to the less standard tags such as Arranger, BPM, Composer, Grouping, Publisher, Composer, etc.

Taglib works great for the standard ones, but in looking at the source, doesn't seem particularly flexible to extend it. Is there any way to currently get at these ID3 frames that I've overlooked?

Thanks!
Ryan

**Comment by supermihi** [comment] 2019-01-02 07:47
Duplicate of #665 - see `Tag::properties()`

**Closed by supermihi** 2019-01-02 07:47 UTC

**Comment by ryanfrancesconi** [comment] 2019-01-02 16:51
ah thanks!
